local icons = FindYourWay.Icons

icons["Inn"] = [[Interface\Minimap\Tracking\Innkeeper]]
icons["Flight Master"] = [[Interface\Minimap\Tracking\FlightMaster]]
icons["Zeppelin"] = [[Interface\Minimap\Tracking\FlightMaster]]
icons["Battle Master"] = [[Interface\Minimap\Tracking\BattleMaster]]
icons["Auction House"] = [[Interface\Minimap\Tracking\Auctioneer]]
icons["Bank"] = [[Interface\Minimap\Tracking\Banker]]
icons["Mailbox"] = [[Interface\Minimap\Tracking\Mailbox]]

icons["Death Knight Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Druid Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Hunter Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Mage Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Priest Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Paladin Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Rogue Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Shaman Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Warlock Trainer"] = [[Interface\Minimap\Tracking\Class]]
icons["Warrior Trainer"] = [[Interface\Minimap\Tracking\Class]]

icons["Alchemy Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Blacksmithing Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Cooking Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Enchanting Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["First Aid Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Fishing Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Herbalism Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Inscription Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Leatherworking Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Mining Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Skinning Trainer"] = [[Interface\Minimap\Tracking\Profession]]
icons["Tailoring Trainer"] = [[Interface\Minimap\Tracking\Profession]]